name: 'MDH_DEMO'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  MDH_DEMO:
    staging:
      materialized: view
      snowflake_warehouse: COMPUTE_WH

tests:
  store_failures: true
  severity: warn

on-run-end:
  - "{{ centralize_test_failures(results) }}"
